spring.application.name=kafka-real-time-attribution
server.port=${PORT:4649}
springdoc.swagger-ui.path=/docs
management.endpoints.web.exposure.include=health,info
spring.jackson.serialization.indent_output=true
